#!/usr/bin/env ruby

require 'rubygems'
require 'facets/shellwords'
require 'ansi'
require 'getoptlong'

class NilClass
  def blank?
    true
  end
end

class String
  def blank?
    self.strip == ""
  end
end

class RLGrep
  attr_accessor :files, :regexp, :file_name, :stdin, :axe_session
  
  def initialize
    parse_arguments
  end
  
  def parse_arguments
    options = GetoptLong.new(
      ['--stdin', '-s', GetoptLong::REQUIRED_ARGUMENT],
      ['--axe-session', '-x', GetoptLong::NO_ARGUMENT]
    )
    options.each do |option, arg|
      case option
      when '--stdin' 
        self.stdin = true
        self.file_name = arg
      when '--axe-session'
        self.axe_session = true
      end
    end
    self.regexp = Regexp.new ARGV.shift
    self.files = ARGV
  end
  
  def puts_file_name_if_needed
    unless @file_name_putted
      puts ANSI.color(:green) {file_name}
      @file_name_putted = true
    end
  end
  
  def block_matches(block)
    block =~ regexp
  end
  
  def each_block
    STDIN.read.split("\n\n").each do |block|
      yield block
    end
  end
  
  
  SESSION_REGEXP = %r"^  Session ID: (\w+\n)+\w+(=*)--\w+\n"m
  
  def start_stdin
    each_block do |block|
      if block_matches(block)
        block = block.gsub(SESSION_REGEXP, '') if axe_session
        puts_file_name_if_needed
        puts block#[SESSION_REGEXP]
      end
    end
  end
  
  def start_multiple
    files.each do |file|
      cat = (file =~ /.gz$/) ? 'gzip -c -d' : 'cat'
      command_line = "#{cat} #{file} | #{$0} --stdin=#{Shellwords::escape(file)} #{Shellwords::escape(regexp.to_s)}"
      command_line += " -x" if axe_session
      # $stderr.puts command_line
      system(command_line)
    end
  end
  
  def start
    if stdin
      start_stdin
    else
      start_multiple
    end
  end
end

RLGrep.new.start